package csen703.test.assignment1;

import csen703.main.assignment1.TheSolisCode;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;

class TheSolisTest {

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon1() {
        String encoded = "4182113";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(10, result);
    }
    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon2() {
        String encoded = "41821130912739816020475613782412893647213654761234078612307846712836478912534786123470913985641723641028736198724012836";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(9953280, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon3() {
        String encoded = "30";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(0, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon4() {
        String encoded = "7213";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(3, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon5() {
        String encoded = "191512919";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(16, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon6() {
        String encoded = "411892119";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(15, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon7() {
        String encoded = "931182119";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(15, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon8() {
        String encoded = "851291519";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(8, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon9() {
        String encoded = "2025";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(3, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon10() {
        String encoded = "308";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(1, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon11() {
        String encoded = "4300812";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(0, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon12() {
        String encoded = "4200812";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(2, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon13() {
        String encoded = "85121215231518124";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(312, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodeDivCon14() {
        String encoded = "9113918151413114";

        int result = TheSolisCode.SolisDecodeDiv(encoded);

        assertEquals(144, result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults1() {
        String encoded = "4182113";
        ArrayList<String> expected = new ArrayList<>(Arrays.asList("drum", "druac", "drbkc", "drbam", "drbaac", "dahum", "dahuac", "dahbkc", "dahbam", "dahbaac"));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults2() {
        String encoded = "32165843216549872132156489721798237814";

        String output = "cufehdcufedihgucuefdhigugihwghn, cufehdcufedihgucuefdhigugihwghad, cufehdcufedihgucuefdhigugihbcghn, cufehdcufedihgucuefdhigugihbcghad, cufehdcufedihgucuefdhigbqihwghn, cufehdcufedihgucuefdhigbqihwghad, cufehdcufedihgucuefdhigbqihbcghn, cufehdcufedihgucuefdhigbqihbcghad, cufehdcufedihgucuefdhigbagihwghn, cufehdcufedihgucuefdhigbagihwghad, cufehdcufedihgucuefdhigbagihbcghn, cufehdcufedihgucuefdhigbagihbcghad, cufehdcufedihgucbofdhigugihwghn, cufehdcufedihgucbofdhigugihwghad, cufehdcufedihgucbofdhigugihbcghn, cufehdcufedihgucbofdhigugihbcghad, cufehdcufedihgucbofdhigbqihwghn, cufehdcufedihgucbofdhigbqihwghad, cufehdcufedihgucbofdhigbqihbcghn, cufehdcufedihgucbofdhigbqihbcghad, cufehdcufedihgucbofdhigbagihwghn, cufehdcufedihgucbofdhigbagihwghad, cufehdcufedihgucbofdhigbagihbcghn, cufehdcufedihgucbofdhigbagihbcghad, cufehdcufedihgucbaefdhigugihwghn, cufehdcufedihgucbaefdhigugihwghad, cufehdcufedihgucbaefdhigugihbcghn, cufehdcufedihgucbaefdhigugihbcghad, cufehdcufedihgucbaefdhigbqihwghn, cufehdcufedihgucbaefdhigbqihwghad, cufehdcufedihgucbaefdhigbqihbcghn, cufehdcufedihgucbaefdhigbqihbcghad, cufehdcufedihgucbaefdhigbagihwghn, cufehdcufedihgucbaefdhigbagihwghad, cufehdcufedihgucbaefdhigbagihbcghn, cufehdcufedihgucbaefdhigbagihbcghad, cufehdcufedihgbmuefdhigugihwghn, cufehdcufedihgbmuefdhigugihwghad, cufehdcufedihgbmuefdhigugihbcghn, cufehdcufedihgbmuefdhigugihbcghad, cufehdcufedihgbmuefdhigbqihwghn, cufehdcufedihgbmuefdhigbqihwghad, cufehdcufedihgbmuefdhigbqihbcghn, cufehdcufedihgbmuefdhigbqihbcghad, cufehdcufedihgbmuefdhigbagihwghn, cufehdcufedihgbmuefdhigbagihwghad, cufehdcufedihgbmuefdhigbagihbcghn, cufehdcufedihgbmuefdhigbagihbcghad, cufehdcufedihgbmbofdhigugihwghn, cufehdcufedihgbmbofdhigugihwghad, cufehdcufedihgbmbofdhigugihbcghn, cufehdcufedihgbmbofdhigugihbcghad, cufehdcufedihgbmbofdhigbqihwghn, cufehdcufedihgbmbofdhigbqihwghad, cufehdcufedihgbmbofdhigbqihbcghn, cufehdcufedihgbmbofdhigbqihbcghad, cufehdcufedihgbmbofdhigbagihwghn, cufehdcufedihgbmbofdhigbagihwghad, cufehdcufedihgbmbofdhigbagihbcghn, cufehdcufedihgbmbofdhigbagihbcghad, cufehdcufedihgbmbaefdhigugihwghn, cufehdcufedihgbmbaefdhigugihwghad, cufehdcufedihgbmbaefdhigugihbcghn, cufehdcufedihgbmbaefdhigugihbcghad, cufehdcufedihgbmbaefdhigbqihwghn, cufehdcufedihgbmbaefdhigbqihwghad, cufehdcufedihgbmbaefdhigbqihbcghn, cufehdcufedihgbmbaefdhigbqihbcghad, cufehdcufedihgbmbaefdhigbagihwghn, cufehdcufedihgbmbaefdhigbagihwghad, cufehdcufedihgbmbaefdhigbagihbcghn, cufehdcufedihgbmbaefdhigbagihbcghad, cufehdcufedihgbacuefdhigugihwghn, cufehdcufedihgbacuefdhigugihwghad, cufehdcufedihgbacuefdhigugihbcghn, cufehdcufedihgbacuefdhigugihbcghad, cufehdcufedihgbacuefdhigbqihwghn, cufehdcufedihgbacuefdhigbqihwghad, cufehdcufedihgbacuefdhigbqihbcghn, cufehdcufedihgbacuefdhigbqihbcghad, cufehdcufedihgbacuefdhigbagihwghn, cufehdcufedihgbacuefdhigbagihwghad, cufehdcufedihgbacuefdhigbagihbcghn, cufehdcufedihgbacuefdhigbagihbcghad, cufehdcufedihgbacbofdhigugihwghn, cufehdcufedihgbacbofdhigugihwghad, cufehdcufedihgbacbofdhigugihbcghn, cufehdcufedihgbacbofdhigugihbcghad, cufehdcufedihgbacbofdhigbqihwghn, cufehdcufedihgbacbofdhigbqihwghad, cufehdcufedihgbacbofdhigbqihbcghn, cufehdcufedihgbacbofdhigbqihbcghad, cufehdcufedihgbacbofdhigbagihwghn, cufehdcufedihgbacbofdhigbagihwghad, cufehdcufedihgbacbofdhigbagihbcghn, cufehdcufedihgbacbofdhigbagihbcghad, cufehdcufedihgbacbaefdhigugihwghn, cufehdcufedihgbacbaefdhigugihwghad, cufehdcufedihgbacbaefdhigugihbcghn, cufehdcufedihgbacbaefdhigugihbcghad, cufehdcufedihgbacbaefdhigbqihwghn, cufehdcufedihgbacbaefdhigbqihwghad, cufehdcufedihgbacbaefdhigbqihbcghn, cufehdcufedihgbacbaefdhigbqihbcghad, cufehdcufedihgbacbaefdhigbagihwghn, cufehdcufedihgbacbaefdhigbagihwghad, cufehdcufedihgbacbaefdhigbagihbcghn, cufehdcufedihgbacbaefdhigbagihbcghad, cufehdcbpedihgucuefdhigugihwghn, cufehdcbpedihgucuefdhigugihwghad, cufehdcbpedihgucuefdhigugihbcghn, cufehdcbpedihgucuefdhigugihbcghad, cufehdcbpedihgucuefdhigbqihwghn, cufehdcbpedihgucuefdhigbqihwghad, cufehdcbpedihgucuefdhigbqihbcghn, cufehdcbpedihgucuefdhigbqihbcghad, cufehdcbpedihgucuefdhigbagihwghn, cufehdcbpedihgucuefdhigbagihwghad, cufehdcbpedihgucuefdhigbagihbcghn, cufehdcbpedihgucuefdhigbagihbcghad, cufehdcbpedihgucbofdhigugihwghn, cufehdcbpedihgucbofdhigugihwghad, cufehdcbpedihgucbofdhigugihbcghn, cufehdcbpedihgucbofdhigugihbcghad, cufehdcbpedihgucbofdhigbqihwghn, cufehdcbpedihgucbofdhigbqihwghad, cufehdcbpedihgucbofdhigbqihbcghn, cufehdcbpedihgucbofdhigbqihbcghad, cufehdcbpedihgucbofdhigbagihwghn, cufehdcbpedihgucbofdhigbagihwghad, cufehdcbpedihgucbofdhigbagihbcghn, cufehdcbpedihgucbofdhigbagihbcghad, cufehdcbpedihgucbaefdhigugihwghn, cufehdcbpedihgucbaefdhigugihwghad, cufehdcbpedihgucbaefdhigugihbcghn, cufehdcbpedihgucbaefdhigugihbcghad, cufehdcbpedihgucbaefdhigbqihwghn, cufehdcbpedihgucbaefdhigbqihwghad, cufehdcbpedihgucbaefdhigbqihbcghn, cufehdcbpedihgucbaefdhigbqihbcghad, cufehdcbpedihgucbaefdhigbagihwghn, cufehdcbpedihgucbaefdhigbagihwghad, cufehdcbpedihgucbaefdhigbagihbcghn, cufehdcbpedihgucbaefdhigbagihbcghad, cufehdcbpedihgbmuefdhigugihwghn, cufehdcbpedihgbmuefdhigugihwghad, cufehdcbpedihgbmuefdhigugihbcghn, cufehdcbpedihgbmuefdhigugihbcghad, cufehdcbpedihgbmuefdhigbqihwghn, cufehdcbpedihgbmuefdhigbqihwghad, cufehdcbpedihgbmuefdhigbqihbcghn, cufehdcbpedihgbmuefdhigbqihbcghad, cufehdcbpedihgbmuefdhigbagihwghn, cufehdcbpedihgbmuefdhigbagihwghad, cufehdcbpedihgbmuefdhigbagihbcghn, cufehdcbpedihgbmuefdhigbagihbcghad, cufehdcbpedihgbmbofdhigugihwghn, cufehdcbpedihgbmbofdhigugihwghad, cufehdcbpedihgbmbofdhigugihbcghn, cufehdcbpedihgbmbofdhigugihbcghad, cufehdcbpedihgbmbofdhigbqihwghn, cufehdcbpedihgbmbofdhigbqihwghad, cufehdcbpedihgbmbofdhigbqihbcghn, cufehdcbpedihgbmbofdhigbqihbcghad, cufehdcbpedihgbmbofdhigbagihwghn, cufehdcbpedihgbmbofdhigbagihwghad, cufehdcbpedihgbmbofdhigbagihbcghn, cufehdcbpedihgbmbofdhigbagihbcghad, cufehdcbpedihgbmbaefdhigugihwghn, cufehdcbpedihgbmbaefdhigugihwghad, cufehdcbpedihgbmbaefdhigugihbcghn, cufehdcbpedihgbmbaefdhigugihbcghad, cufehdcbpedihgbmbaefdhigbqihwghn, cufehdcbpedihgbmbaefdhigbqihwghad, cufehdcbpedihgbmbaefdhigbqihbcghn, cufehdcbpedihgbmbaefdhigbqihbcghad, cufehdcbpedihgbmbaefdhigbagihwghn, cufehdcbpedihgbmbaefdhigbagihwghad, cufehdcbpedihgbmbaefdhigbagihbcghn, cufehdcbpedihgbmbaefdhigbagihbcghad, cufehdcbpedihgbacuefdhigugihwghn, cufehdcbpedihgbacuefdhigugihwghad, cufehdcbpedihgbacuefdhigugihbcghn, cufehdcbpedihgbacuefdhigugihbcghad, cufehdcbpedihgbacuefdhigbqihwghn, cufehdcbpedihgbacuefdhigbqihwghad, cufehdcbpedihgbacuefdhigbqihbcghn, cufehdcbpedihgbacuefdhigbqihbcghad, cufehdcbpedihgbacuefdhigbagihwghn, cufehdcbpedihgbacuefdhigbagihwghad, cufehdcbpedihgbacuefdhigbagihbcghn, cufehdcbpedihgbacuefdhigbagihbcghad, cufehdcbpedihgbacbofdhigugihwghn, cufehdcbpedihgbacbofdhigugihwghad, cufehdcbpedihgbacbofdhigugihbcghn, cufehdcbpedihgbacbofdhigugihbcghad, cufehdcbpedihgbacbofdhigbqihwghn, cufehdcbpedihgbacbofdhigbqihwghad, cufehdcbpedihgbacbofdhigbqihbcghn, cufehdcbpedihgbacbofdhigbqihbcghad, cufehdcbpedihgbacbofdhigbagihwghn, cufehdcbpedihgbacbofdhigbagihwghad, cufehdcbpedihgbacbofdhigbagihbcghn, cufehdcbpedihgbacbofdhigbagihbcghad, cufehdcbpedihgbacbaefdhigugihwghn, cufehdcbpedihgbacbaefdhigugihwghad, cufehdcbpedihgbacbaefdhigugihbcghn, cufehdcbpedihgbacbaefdhigugihbcghad, cufehdcbpedihgbacbaefdhigbqihwghn, cufehdcbpedihgbacbaefdhigbqihwghad, cufehdcbpedihgbacbaefdhigbqihbcghn, cufehdcbpedihgbacbaefdhigbqihbcghad, cufehdcbpedihgbacbaefdhigbagihwghn, cufehdcbpedihgbacbaefdhigbagihwghad, cufehdcbpedihgbacbaefdhigbagihbcghn, cufehdcbpedihgbacbaefdhigbagihbcghad, cufehdcbafedihgucuefdhigugihwghn, cufehdcbafedihgucuefdhigugihwghad, cufehdcbafedihgucuefdhigugihbcghn, cufehdcbafedihgucuefdhigugihbcghad, cufehdcbafedihgucuefdhigbqihwghn, cufehdcbafedihgucuefdhigbqihwghad, cufehdcbafedihgucuefdhigbqihbcghn, cufehdcbafedihgucuefdhigbqihbcghad, cufehdcbafedihgucuefdhigbagihwghn, cufehdcbafedihgucuefdhigbagihwghad, cufehdcbafedihgucuefdhigbagihbcghn, cufehdcbafedihgucuefdhigbagihbcghad, cufehdcbafedihgucbofdhigugihwghn, cufehdcbafedihgucbofdhigugihwghad, cufehdcbafedihgucbofdhigugihbcghn, cufehdcbafedihgucbofdhigugihbcghad, cufehdcbafedihgucbofdhigbqihwghn, cufehdcbafedihgucbofdhigbqihwghad, cufehdcbafedihgucbofdhigbqihbcghn, cufehdcbafedihgucbofdhigbqihbcghad, cufehdcbafedihgucbofdhigbagihwghn, cufehdcbafedihgucbofdhigbagihwghad, cufehdcbafedihgucbofdhigbagihbcghn, cufehdcbafedihgucbofdhigbagihbcghad, cufehdcbafedihgucbaefdhigugihwghn, cufehdcbafedihgucbaefdhigugihwghad, cufehdcbafedihgucbaefdhigugihbcghn, cufehdcbafedihgucbaefdhigugihbcghad, cufehdcbafedihgucbaefdhigbqihwghn, cufehdcbafedihgucbaefdhigbqihwghad, cufehdcbafedihgucbaefdhigbqihbcghn, cufehdcbafedihgucbaefdhigbqihbcghad, cufehdcbafedihgucbaefdhigbagihwghn, cufehdcbafedihgucbaefdhigbagihwghad, cufehdcbafedihgucbaefdhigbagihbcghn, cufehdcbafedihgucbaefdhigbagihbcghad, cufehdcbafedihgbmuefdhigugihwghn, cufehdcbafedihgbmuefdhigugihwghad, cufehdcbafedihgbmuefdhigugihbcghn, cufehdcbafedihgbmuefdhigugihbcghad, cufehdcbafedihgbmuefdhigbqihwghn, cufehdcbafedihgbmuefdhigbqihwghad, cufehdcbafedihgbmuefdhigbqihbcghn, cufehdcbafedihgbmuefdhigbqihbcghad, cufehdcbafedihgbmuefdhigbagihwghn, cufehdcbafedihgbmuefdhigbagihwghad, cufehdcbafedihgbmuefdhigbagihbcghn, cufehdcbafedihgbmuefdhigbagihbcghad, cufehdcbafedihgbmbofdhigugihwghn, cufehdcbafedihgbmbofdhigugihwghad, cufehdcbafedihgbmbofdhigugihbcghn, cufehdcbafedihgbmbofdhigugihbcghad, cufehdcbafedihgbmbofdhigbqihwghn, cufehdcbafedihgbmbofdhigbqihwghad, cufehdcbafedihgbmbofdhigbqihbcghn, cufehdcbafedihgbmbofdhigbqihbcghad, cufehdcbafedihgbmbofdhigbagihwghn, cufehdcbafedihgbmbofdhigbagihwghad, cufehdcbafedihgbmbofdhigbagihbcghn, cufehdcbafedihgbmbofdhigbagihbcghad, cufehdcbafedihgbmbaefdhigugihwghn, cufehdcbafedihgbmbaefdhigugihwghad, cufehdcbafedihgbmbaefdhigugihbcghn, cufehdcbafedihgbmbaefdhigugihbcghad, cufehdcbafedihgbmbaefdhigbqihwghn, cufehdcbafedihgbmbaefdhigbqihwghad, cufehdcbafedihgbmbaefdhigbqihbcghn, cufehdcbafedihgbmbaefdhigbqihbcghad, cufehdcbafedihgbmbaefdhigbagihwghn, cufehdcbafedihgbmbaefdhigbagihwghad, cufehdcbafedihgbmbaefdhigbagihbcghn, cufehdcbafedihgbmbaefdhigbagihbcghad, cufehdcbafedihgbacuefdhigugihwghn, cufehdcbafedihgbacuefdhigugihwghad, cufehdcbafedihgbacuefdhigugihbcghn, cufehdcbafedihgbacuefdhigugihbcghad, cufehdcbafedihgbacuefdhigbqihwghn, cufehdcbafedihgbacuefdhigbqihwghad, cufehdcbafedihgbacuefdhigbqihbcghn, cufehdcbafedihgbacuefdhigbqihbcghad, cufehdcbafedihgbacuefdhigbagihwghn, cufehdcbafedihgbacuefdhigbagihwghad, cufehdcbafedihgbacuefdhigbagihbcghn, cufehdcbafedihgbacuefdhigbagihbcghad, cufehdcbafedihgbacbofdhigugihwghn, cufehdcbafedihgbacbofdhigugihwghad, cufehdcbafedihgbacbofdhigugihbcghn, cufehdcbafedihgbacbofdhigugihbcghad, cufehdcbafedihgbacbofdhigbqihwghn, cufehdcbafedihgbacbofdhigbqihwghad, cufehdcbafedihgbacbofdhigbqihbcghn, cufehdcbafedihgbacbofdhigbqihbcghad, cufehdcbafedihgbacbofdhigbagihwghn, cufehdcbafedihgbacbofdhigbagihwghad, cufehdcbafedihgbacbofdhigbagihbcghn, cufehdcbafedihgbacbofdhigbagihbcghad, cufehdcbafedihgbacbaefdhigugihwghn, cufehdcbafedihgbacbaefdhigugihwghad, cufehdcbafedihgbacbaefdhigugihbcghn, cufehdcbafedihgbacbaefdhigugihbcghad, cufehdcbafedihgbacbaefdhigbqihwghn, cufehdcbafedihgbacbaefdhigbqihwghad, cufehdcbafedihgbacbaefdhigbqihbcghn, cufehdcbafedihgbacbaefdhigbqihbcghad, cufehdcbafedihgbacbaefdhigbagihwghn, cufehdcbafedihgbacbaefdhigbagihwghad, cufehdcbafedihgbacbaefdhigbagihbcghn, cufehdcbafedihgbacbaefdhigbagihbcghad, cbpehdcufedihgucuefdhigugihwghn, cbpehdcufedihgucuefdhigugihwghad, cbpehdcufedihgucuefdhigugihbcghn, cbpehdcufedihgucuefdhigugihbcghad, cbpehdcufedihgucuefdhigbqihwghn, cbpehdcufedihgucuefdhigbqihwghad, cbpehdcufedihgucuefdhigbqihbcghn, cbpehdcufedihgucuefdhigbqihbcghad, cbpehdcufedihgucuefdhigbagihwghn, cbpehdcufedihgucuefdhigbagihwghad, cbpehdcufedihgucuefdhigbagihbcghn, cbpehdcufedihgucuefdhigbagihbcghad, cbpehdcufedihgucbofdhigugihwghn, cbpehdcufedihgucbofdhigugihwghad, cbpehdcufedihgucbofdhigugihbcghn, cbpehdcufedihgucbofdhigugihbcghad, cbpehdcufedihgucbofdhigbqihwghn, cbpehdcufedihgucbofdhigbqihwghad, cbpehdcufedihgucbofdhigbqihbcghn, cbpehdcufedihgucbofdhigbqihbcghad, cbpehdcufedihgucbofdhigbagihwghn, cbpehdcufedihgucbofdhigbagihwghad, cbpehdcufedihgucbofdhigbagihbcghn, cbpehdcufedihgucbofdhigbagihbcghad, cbpehdcufedihgucbaefdhigugihwghn, cbpehdcufedihgucbaefdhigugihwghad, cbpehdcufedihgucbaefdhigugihbcghn, cbpehdcufedihgucbaefdhigugihbcghad, cbpehdcufedihgucbaefdhigbqihwghn, cbpehdcufedihgucbaefdhigbqihwghad, cbpehdcufedihgucbaefdhigbqihbcghn, cbpehdcufedihgucbaefdhigbqihbcghad, cbpehdcufedihgucbaefdhigbagihwghn, cbpehdcufedihgucbaefdhigbagihwghad, cbpehdcufedihgucbaefdhigbagihbcghn, cbpehdcufedihgucbaefdhigbagihbcghad, cbpehdcufedihgbmuefdhigugihwghn, cbpehdcufedihgbmuefdhigugihwghad, cbpehdcufedihgbmuefdhigugihbcghn, cbpehdcufedihgbmuefdhigugihbcghad, cbpehdcufedihgbmuefdhigbqihwghn, cbpehdcufedihgbmuefdhigbqihwghad, cbpehdcufedihgbmuefdhigbqihbcghn, cbpehdcufedihgbmuefdhigbqihbcghad, cbpehdcufedihgbmuefdhigbagihwghn, cbpehdcufedihgbmuefdhigbagihwghad, cbpehdcufedihgbmuefdhigbagihbcghn, cbpehdcufedihgbmuefdhigbagihbcghad, cbpehdcufedihgbmbofdhigugihwghn, cbpehdcufedihgbmbofdhigugihwghad, cbpehdcufedihgbmbofdhigugihbcghn, cbpehdcufedihgbmbofdhigugihbcghad, cbpehdcufedihgbmbofdhigbqihwghn, cbpehdcufedihgbmbofdhigbqihwghad, cbpehdcufedihgbmbofdhigbqihbcghn, cbpehdcufedihgbmbofdhigbqihbcghad, cbpehdcufedihgbmbofdhigbagihwghn, cbpehdcufedihgbmbofdhigbagihwghad, cbpehdcufedihgbmbofdhigbagihbcghn, cbpehdcufedihgbmbofdhigbagihbcghad, cbpehdcufedihgbmbaefdhigugihwghn, cbpehdcufedihgbmbaefdhigugihwghad, cbpehdcufedihgbmbaefdhigugihbcghn, cbpehdcufedihgbmbaefdhigugihbcghad, cbpehdcufedihgbmbaefdhigbqihwghn, cbpehdcufedihgbmbaefdhigbqihwghad, cbpehdcufedihgbmbaefdhigbqihbcghn, cbpehdcufedihgbmbaefdhigbqihbcghad, cbpehdcufedihgbmbaefdhigbagihwghn, cbpehdcufedihgbmbaefdhigbagihwghad, cbpehdcufedihgbmbaefdhigbagihbcghn, cbpehdcufedihgbmbaefdhigbagihbcghad, cbpehdcufedihgbacuefdhigugihwghn, cbpehdcufedihgbacuefdhigugihwghad, cbpehdcufedihgbacuefdhigugihbcghn, cbpehdcufedihgbacuefdhigugihbcghad, cbpehdcufedihgbacuefdhigbqihwghn, cbpehdcufedihgbacuefdhigbqihwghad, cbpehdcufedihgbacuefdhigbqihbcghn, cbpehdcufedihgbacuefdhigbqihbcghad, cbpehdcufedihgbacuefdhigbagihwghn, cbpehdcufedihgbacuefdhigbagihwghad, cbpehdcufedihgbacuefdhigbagihbcghn, cbpehdcufedihgbacuefdhigbagihbcghad, cbpehdcufedihgbacbofdhigugihwghn, cbpehdcufedihgbacbofdhigugihwghad, cbpehdcufedihgbacbofdhigugihbcghn, cbpehdcufedihgbacbofdhigugihbcghad, cbpehdcufedihgbacbofdhigbqihwghn, cbpehdcufedihgbacbofdhigbqihwghad, cbpehdcufedihgbacbofdhigbqihbcghn, cbpehdcufedihgbacbofdhigbqihbcghad, cbpehdcufedihgbacbofdhigbagihwghn, cbpehdcufedihgbacbofdhigbagihwghad, cbpehdcufedihgbacbofdhigbagihbcghn, cbpehdcufedihgbacbofdhigbagihbcghad, cbpehdcufedihgbacbaefdhigugihwghn, cbpehdcufedihgbacbaefdhigugihwghad, cbpehdcufedihgbacbaefdhigugihbcghn, cbpehdcufedihgbacbaefdhigugihbcghad, cbpehdcufedihgbacbaefdhigbqihwghn, cbpehdcufedihgbacbaefdhigbqihwghad, cbpehdcufedihgbacbaefdhigbqihbcghn, cbpehdcufedihgbacbaefdhigbqihbcghad, cbpehdcufedihgbacbaefdhigbagihwghn, cbpehdcufedihgbacbaefdhigbagihwghad, cbpehdcufedihgbacbaefdhigbagihbcghn, cbpehdcufedihgbacbaefdhigbagihbcghad, cbpehdcbpedihgucuefdhigugihwghn, cbpehdcbpedihgucuefdhigugihwghad, cbpehdcbpedihgucuefdhigugihbcghn, cbpehdcbpedihgucuefdhigugihbcghad, cbpehdcbpedihgucuefdhigbqihwghn, cbpehdcbpedihgucuefdhigbqihwghad, cbpehdcbpedihgucuefdhigbqihbcghn, cbpehdcbpedihgucuefdhigbqihbcghad, cbpehdcbpedihgucuefdhigbagihwghn, cbpehdcbpedihgucuefdhigbagihwghad, cbpehdcbpedihgucuefdhigbagihbcghn, cbpehdcbpedihgucuefdhigbagihbcghad, cbpehdcbpedihgucbofdhigugihwghn, cbpehdcbpedihgucbofdhigugihwghad, cbpehdcbpedihgucbofdhigugihbcghn, cbpehdcbpedihgucbofdhigugihbcghad, cbpehdcbpedihgucbofdhigbqihwghn, cbpehdcbpedihgucbofdhigbqihwghad, cbpehdcbpedihgucbofdhigbqihbcghn, cbpehdcbpedihgucbofdhigbqihbcghad, cbpehdcbpedihgucbofdhigbagihwghn, cbpehdcbpedihgucbofdhigbagihwghad, cbpehdcbpedihgucbofdhigbagihbcghn, cbpehdcbpedihgucbofdhigbagihbcghad, cbpehdcbpedihgucbaefdhigugihwghn, cbpehdcbpedihgucbaefdhigugihwghad, cbpehdcbpedihgucbaefdhigugihbcghn, cbpehdcbpedihgucbaefdhigugihbcghad, cbpehdcbpedihgucbaefdhigbqihwghn, cbpehdcbpedihgucbaefdhigbqihwghad, cbpehdcbpedihgucbaefdhigbqihbcghn, cbpehdcbpedihgucbaefdhigbqihbcghad, cbpehdcbpedihgucbaefdhigbagihwghn, cbpehdcbpedihgucbaefdhigbagihwghad, cbpehdcbpedihgucbaefdhigbagihbcghn, cbpehdcbpedihgucbaefdhigbagihbcghad, cbpehdcbpedihgbmuefdhigugihwghn, cbpehdcbpedihgbmuefdhigugihwghad, cbpehdcbpedihgbmuefdhigugihbcghn, cbpehdcbpedihgbmuefdhigugihbcghad, cbpehdcbpedihgbmuefdhigbqihwghn, cbpehdcbpedihgbmuefdhigbqihwghad, cbpehdcbpedihgbmuefdhigbqihbcghn, cbpehdcbpedihgbmuefdhigbqihbcghad, cbpehdcbpedihgbmuefdhigbagihwghn, cbpehdcbpedihgbmuefdhigbagihwghad, cbpehdcbpedihgbmuefdhigbagihbcghn, cbpehdcbpedihgbmuefdhigbagihbcghad, cbpehdcbpedihgbmbofdhigugihwghn, cbpehdcbpedihgbmbofdhigugihwghad, cbpehdcbpedihgbmbofdhigugihbcghn, cbpehdcbpedihgbmbofdhigugihbcghad, cbpehdcbpedihgbmbofdhigbqihwghn, cbpehdcbpedihgbmbofdhigbqihwghad, cbpehdcbpedihgbmbofdhigbqihbcghn, cbpehdcbpedihgbmbofdhigbqihbcghad, cbpehdcbpedihgbmbofdhigbagihwghn, cbpehdcbpedihgbmbofdhigbagihwghad, cbpehdcbpedihgbmbofdhigbagihbcghn, cbpehdcbpedihgbmbofdhigbagihbcghad, cbpehdcbpedihgbmbaefdhigugihwghn, cbpehdcbpedihgbmbaefdhigugihwghad, cbpehdcbpedihgbmbaefdhigugihbcghn, cbpehdcbpedihgbmbaefdhigugihbcghad, cbpehdcbpedihgbmbaefdhigbqihwghn, cbpehdcbpedihgbmbaefdhigbqihwghad, cbpehdcbpedihgbmbaefdhigbqihbcghn, cbpehdcbpedihgbmbaefdhigbqihbcghad, cbpehdcbpedihgbmbaefdhigbagihwghn, cbpehdcbpedihgbmbaefdhigbagihwghad, cbpehdcbpedihgbmbaefdhigbagihbcghn, cbpehdcbpedihgbmbaefdhigbagihbcghad, cbpehdcbpedihgbacuefdhigugihwghn, cbpehdcbpedihgbacuefdhigugihwghad, cbpehdcbpedihgbacuefdhigugihbcghn, cbpehdcbpedihgbacuefdhigugihbcghad, cbpehdcbpedihgbacuefdhigbqihwghn, cbpehdcbpedihgbacuefdhigbqihwghad, cbpehdcbpedihgbacuefdhigbqihbcghn, cbpehdcbpedihgbacuefdhigbqihbcghad, cbpehdcbpedihgbacuefdhigbagihwghn, cbpehdcbpedihgbacuefdhigbagihwghad, cbpehdcbpedihgbacuefdhigbagihbcghn, cbpehdcbpedihgbacuefdhigbagihbcghad, cbpehdcbpedihgbacbofdhigugihwghn, cbpehdcbpedihgbacbofdhigugihwghad, cbpehdcbpedihgbacbofdhigugihbcghn, cbpehdcbpedihgbacbofdhigugihbcghad, cbpehdcbpedihgbacbofdhigbqihwghn, cbpehdcbpedihgbacbofdhigbqihwghad, cbpehdcbpedihgbacbofdhigbqihbcghn, cbpehdcbpedihgbacbofdhigbqihbcghad, cbpehdcbpedihgbacbofdhigbagihwghn, cbpehdcbpedihgbacbofdhigbagihwghad, cbpehdcbpedihgbacbofdhigbagihbcghn, cbpehdcbpedihgbacbofdhigbagihbcghad, cbpehdcbpedihgbacbaefdhigugihwghn, cbpehdcbpedihgbacbaefdhigugihwghad, cbpehdcbpedihgbacbaefdhigugihbcghn, cbpehdcbpedihgbacbaefdhigugihbcghad, cbpehdcbpedihgbacbaefdhigbqihwghn, cbpehdcbpedihgbacbaefdhigbqihwghad, cbpehdcbpedihgbacbaefdhigbqihbcghn, cbpehdcbpedihgbacbaefdhigbqihbcghad, cbpehdcbpedihgbacbaefdhigbagihwghn, cbpehdcbpedihgbacbaefdhigbagihwghad, cbpehdcbpedihgbacbaefdhigbagihbcghn, cbpehdcbpedihgbacbaefdhigbagihbcghad, cbpehdcbafedihgucuefdhigugihwghn, cbpehdcbafedihgucuefdhigugihwghad, cbpehdcbafedihgucuefdhigugihbcghn, cbpehdcbafedihgucuefdhigugihbcghad, cbpehdcbafedihgucuefdhigbqihwghn, cbpehdcbafedihgucuefdhigbqihwghad, cbpehdcbafedihgucuefdhigbqihbcghn, cbpehdcbafedihgucuefdhigbqihbcghad, cbpehdcbafedihgucuefdhigbagihwghn, cbpehdcbafedihgucuefdhigbagihwghad, cbpehdcbafedihgucuefdhigbagihbcghn, cbpehdcbafedihgucuefdhigbagihbcghad, cbpehdcbafedihgucbofdhigugihwghn, cbpehdcbafedihgucbofdhigugihwghad, cbpehdcbafedihgucbofdhigugihbcghn, cbpehdcbafedihgucbofdhigugihbcghad, cbpehdcbafedihgucbofdhigbqihwghn, cbpehdcbafedihgucbofdhigbqihwghad, cbpehdcbafedihgucbofdhigbqihbcghn, cbpehdcbafedihgucbofdhigbqihbcghad, cbpehdcbafedihgucbofdhigbagihwghn, cbpehdcbafedihgucbofdhigbagihwghad, cbpehdcbafedihgucbofdhigbagihbcghn, cbpehdcbafedihgucbofdhigbagihbcghad, cbpehdcbafedihgucbaefdhigugihwghn, cbpehdcbafedihgucbaefdhigugihwghad, cbpehdcbafedihgucbaefdhigugihbcghn, cbpehdcbafedihgucbaefdhigugihbcghad, cbpehdcbafedihgucbaefdhigbqihwghn, cbpehdcbafedihgucbaefdhigbqihwghad, cbpehdcbafedihgucbaefdhigbqihbcghn, cbpehdcbafedihgucbaefdhigbqihbcghad, cbpehdcbafedihgucbaefdhigbagihwghn, cbpehdcbafedihgucbaefdhigbagihwghad, cbpehdcbafedihgucbaefdhigbagihbcghn, cbpehdcbafedihgucbaefdhigbagihbcghad, cbpehdcbafedihgbmuefdhigugihwghn, cbpehdcbafedihgbmuefdhigugihwghad, cbpehdcbafedihgbmuefdhigugihbcghn, cbpehdcbafedihgbmuefdhigugihbcghad, cbpehdcbafedihgbmuefdhigbqihwghn, cbpehdcbafedihgbmuefdhigbqihwghad, cbpehdcbafedihgbmuefdhigbqihbcghn, cbpehdcbafedihgbmuefdhigbqihbcghad, cbpehdcbafedihgbmuefdhigbagihwghn, cbpehdcbafedihgbmuefdhigbagihwghad, cbpehdcbafedihgbmuefdhigbagihbcghn, cbpehdcbafedihgbmuefdhigbagihbcghad, cbpehdcbafedihgbmbofdhigugihwghn, cbpehdcbafedihgbmbofdhigugihwghad, cbpehdcbafedihgbmbofdhigugihbcghn, cbpehdcbafedihgbmbofdhigugihbcghad, cbpehdcbafedihgbmbofdhigbqihwghn, cbpehdcbafedihgbmbofdhigbqihwghad, cbpehdcbafedihgbmbofdhigbqihbcghn, cbpehdcbafedihgbmbofdhigbqihbcghad, cbpehdcbafedihgbmbofdhigbagihwghn, cbpehdcbafedihgbmbofdhigbagihwghad, cbpehdcbafedihgbmbofdhigbagihbcghn, cbpehdcbafedihgbmbofdhigbagihbcghad, cbpehdcbafedihgbmbaefdhigugihwghn, cbpehdcbafedihgbmbaefdhigugihwghad, cbpehdcbafedihgbmbaefdhigugihbcghn, cbpehdcbafedihgbmbaefdhigugihbcghad, cbpehdcbafedihgbmbaefdhigbqihwghn, cbpehdcbafedihgbmbaefdhigbqihwghad, cbpehdcbafedihgbmbaefdhigbqihbcghn, cbpehdcbafedihgbmbaefdhigbqihbcghad, cbpehdcbafedihgbmbaefdhigbagihwghn, cbpehdcbafedihgbmbaefdhigbagihwghad, cbpehdcbafedihgbmbaefdhigbagihbcghn, cbpehdcbafedihgbmbaefdhigbagihbcghad, cbpehdcbafedihgbacuefdhigugihwghn, cbpehdcbafedihgbacuefdhigugihwghad, cbpehdcbafedihgbacuefdhigugihbcghn, cbpehdcbafedihgbacuefdhigugihbcghad, cbpehdcbafedihgbacuefdhigbqihwghn, cbpehdcbafedihgbacuefdhigbqihwghad, cbpehdcbafedihgbacuefdhigbqihbcghn, cbpehdcbafedihgbacuefdhigbqihbcghad, cbpehdcbafedihgbacuefdhigbagihwghn, cbpehdcbafedihgbacuefdhigbagihwghad, cbpehdcbafedihgbacuefdhigbagihbcghn, cbpehdcbafedihgbacuefdhigbagihbcghad, cbpehdcbafedihgbacbofdhigugihwghn, cbpehdcbafedihgbacbofdhigugihwghad, cbpehdcbafedihgbacbofdhigugihbcghn, cbpehdcbafedihgbacbofdhigugihbcghad, cbpehdcbafedihgbacbofdhigbqihwghn, cbpehdcbafedihgbacbofdhigbqihwghad, cbpehdcbafedihgbacbofdhigbqihbcghn, cbpehdcbafedihgbacbofdhigbqihbcghad, cbpehdcbafedihgbacbofdhigbagihwghn, cbpehdcbafedihgbacbofdhigbagihwghad, cbpehdcbafedihgbacbofdhigbagihbcghn, cbpehdcbafedihgbacbofdhigbagihbcghad, cbpehdcbafedihgbacbaefdhigugihwghn, cbpehdcbafedihgbacbaefdhigugihwghad, cbpehdcbafedihgbacbaefdhigugihbcghn, cbpehdcbafedihgbacbaefdhigugihbcghad, cbpehdcbafedihgbacbaefdhigbqihwghn, cbpehdcbafedihgbacbaefdhigbqihwghad, cbpehdcbafedihgbacbaefdhigbqihbcghn, cbpehdcbafedihgbacbaefdhigbqihbcghad, cbpehdcbafedihgbacbaefdhigbagihwghn, cbpehdcbafedihgbacbaefdhigbagihwghad, cbpehdcbafedihgbacbaefdhigbagihbcghn, cbpehdcbafedihgbacbaefdhigbagihbcghad, cbafehdcufedihgucuefdhigugihwghn, cbafehdcufedihgucuefdhigugihwghad, cbafehdcufedihgucuefdhigugihbcghn, cbafehdcufedihgucuefdhigugihbcghad, cbafehdcufedihgucuefdhigbqihwghn, cbafehdcufedihgucuefdhigbqihwghad, cbafehdcufedihgucuefdhigbqihbcghn, cbafehdcufedihgucuefdhigbqihbcghad, cbafehdcufedihgucuefdhigbagihwghn, cbafehdcufedihgucuefdhigbagihwghad, cbafehdcufedihgucuefdhigbagihbcghn, cbafehdcufedihgucuefdhigbagihbcghad, cbafehdcufedihgucbofdhigugihwghn, cbafehdcufedihgucbofdhigugihwghad, cbafehdcufedihgucbofdhigugihbcghn, cbafehdcufedihgucbofdhigugihbcghad, cbafehdcufedihgucbofdhigbqihwghn, cbafehdcufedihgucbofdhigbqihwghad, cbafehdcufedihgucbofdhigbqihbcghn, cbafehdcufedihgucbofdhigbqihbcghad, cbafehdcufedihgucbofdhigbagihwghn, cbafehdcufedihgucbofdhigbagihwghad, cbafehdcufedihgucbofdhigbagihbcghn, cbafehdcufedihgucbofdhigbagihbcghad, cbafehdcufedihgucbaefdhigugihwghn, cbafehdcufedihgucbaefdhigugihwghad, cbafehdcufedihgucbaefdhigugihbcghn, cbafehdcufedihgucbaefdhigugihbcghad, cbafehdcufedihgucbaefdhigbqihwghn, cbafehdcufedihgucbaefdhigbqihwghad, cbafehdcufedihgucbaefdhigbqihbcghn, cbafehdcufedihgucbaefdhigbqihbcghad, cbafehdcufedihgucbaefdhigbagihwghn, cbafehdcufedihgucbaefdhigbagihwghad, cbafehdcufedihgucbaefdhigbagihbcghn, cbafehdcufedihgucbaefdhigbagihbcghad, cbafehdcufedihgbmuefdhigugihwghn, cbafehdcufedihgbmuefdhigugihwghad, cbafehdcufedihgbmuefdhigugihbcghn, cbafehdcufedihgbmuefdhigugihbcghad, cbafehdcufedihgbmuefdhigbqihwghn, cbafehdcufedihgbmuefdhigbqihwghad, cbafehdcufedihgbmuefdhigbqihbcghn, cbafehdcufedihgbmuefdhigbqihbcghad, cbafehdcufedihgbmuefdhigbagihwghn, cbafehdcufedihgbmuefdhigbagihwghad, cbafehdcufedihgbmuefdhigbagihbcghn, cbafehdcufedihgbmuefdhigbagihbcghad, cbafehdcufedihgbmbofdhigugihwghn, cbafehdcufedihgbmbofdhigugihwghad, cbafehdcufedihgbmbofdhigugihbcghn, cbafehdcufedihgbmbofdhigugihbcghad, cbafehdcufedihgbmbofdhigbqihwghn, cbafehdcufedihgbmbofdhigbqihwghad, cbafehdcufedihgbmbofdhigbqihbcghn, cbafehdcufedihgbmbofdhigbqihbcghad, cbafehdcufedihgbmbofdhigbagihwghn, cbafehdcufedihgbmbofdhigbagihwghad, cbafehdcufedihgbmbofdhigbagihbcghn, cbafehdcufedihgbmbofdhigbagihbcghad, cbafehdcufedihgbmbaefdhigugihwghn, cbafehdcufedihgbmbaefdhigugihwghad, cbafehdcufedihgbmbaefdhigugihbcghn, cbafehdcufedihgbmbaefdhigugihbcghad, cbafehdcufedihgbmbaefdhigbqihwghn, cbafehdcufedihgbmbaefdhigbqihwghad, cbafehdcufedihgbmbaefdhigbqihbcghn, cbafehdcufedihgbmbaefdhigbqihbcghad, cbafehdcufedihgbmbaefdhigbagihwghn, cbafehdcufedihgbmbaefdhigbagihwghad, cbafehdcufedihgbmbaefdhigbagihbcghn, cbafehdcufedihgbmbaefdhigbagihbcghad, cbafehdcufedihgbacuefdhigugihwghn, cbafehdcufedihgbacuefdhigugihwghad, cbafehdcufedihgbacuefdhigugihbcghn, cbafehdcufedihgbacuefdhigugihbcghad, cbafehdcufedihgbacuefdhigbqihwghn, cbafehdcufedihgbacuefdhigbqihwghad, cbafehdcufedihgbacuefdhigbqihbcghn, cbafehdcufedihgbacuefdhigbqihbcghad, cbafehdcufedihgbacuefdhigbagihwghn, cbafehdcufedihgbacuefdhigbagihwghad, cbafehdcufedihgbacuefdhigbagihbcghn, cbafehdcufedihgbacuefdhigbagihbcghad, cbafehdcufedihgbacbofdhigugihwghn, cbafehdcufedihgbacbofdhigugihwghad, cbafehdcufedihgbacbofdhigugihbcghn, cbafehdcufedihgbacbofdhigugihbcghad, cbafehdcufedihgbacbofdhigbqihwghn, cbafehdcufedihgbacbofdhigbqihwghad, cbafehdcufedihgbacbofdhigbqihbcghn, cbafehdcufedihgbacbofdhigbqihbcghad, cbafehdcufedihgbacbofdhigbagihwghn, cbafehdcufedihgbacbofdhigbagihwghad, cbafehdcufedihgbacbofdhigbagihbcghn, cbafehdcufedihgbacbofdhigbagihbcghad, cbafehdcufedihgbacbaefdhigugihwghn, cbafehdcufedihgbacbaefdhigugihwghad, cbafehdcufedihgbacbaefdhigugihbcghn, cbafehdcufedihgbacbaefdhigugihbcghad, cbafehdcufedihgbacbaefdhigbqihwghn, cbafehdcufedihgbacbaefdhigbqihwghad, cbafehdcufedihgbacbaefdhigbqihbcghn, cbafehdcufedihgbacbaefdhigbqihbcghad, cbafehdcufedihgbacbaefdhigbagihwghn, cbafehdcufedihgbacbaefdhigbagihwghad, cbafehdcufedihgbacbaefdhigbagihbcghn, cbafehdcufedihgbacbaefdhigbagihbcghad, cbafehdcbpedihgucuefdhigugihwghn, cbafehdcbpedihgucuefdhigugihwghad, cbafehdcbpedihgucuefdhigugihbcghn, cbafehdcbpedihgucuefdhigugihbcghad, cbafehdcbpedihgucuefdhigbqihwghn, cbafehdcbpedihgucuefdhigbqihwghad, cbafehdcbpedihgucuefdhigbqihbcghn, cbafehdcbpedihgucuefdhigbqihbcghad, cbafehdcbpedihgucuefdhigbagihwghn, cbafehdcbpedihgucuefdhigbagihwghad, cbafehdcbpedihgucuefdhigbagihbcghn, cbafehdcbpedihgucuefdhigbagihbcghad, cbafehdcbpedihgucbofdhigugihwghn, cbafehdcbpedihgucbofdhigugihwghad, cbafehdcbpedihgucbofdhigugihbcghn, cbafehdcbpedihgucbofdhigugihbcghad, cbafehdcbpedihgucbofdhigbqihwghn, cbafehdcbpedihgucbofdhigbqihwghad, cbafehdcbpedihgucbofdhigbqihbcghn, cbafehdcbpedihgucbofdhigbqihbcghad, cbafehdcbpedihgucbofdhigbagihwghn, cbafehdcbpedihgucbofdhigbagihwghad, cbafehdcbpedihgucbofdhigbagihbcghn, cbafehdcbpedihgucbofdhigbagihbcghad, cbafehdcbpedihgucbaefdhigugihwghn, cbafehdcbpedihgucbaefdhigugihwghad, cbafehdcbpedihgucbaefdhigugihbcghn, cbafehdcbpedihgucbaefdhigugihbcghad, cbafehdcbpedihgucbaefdhigbqihwghn, cbafehdcbpedihgucbaefdhigbqihwghad, cbafehdcbpedihgucbaefdhigbqihbcghn, cbafehdcbpedihgucbaefdhigbqihbcghad, cbafehdcbpedihgucbaefdhigbagihwghn, cbafehdcbpedihgucbaefdhigbagihwghad, cbafehdcbpedihgucbaefdhigbagihbcghn, cbafehdcbpedihgucbaefdhigbagihbcghad, cbafehdcbpedihgbmuefdhigugihwghn, cbafehdcbpedihgbmuefdhigugihwghad, cbafehdcbpedihgbmuefdhigugihbcghn, cbafehdcbpedihgbmuefdhigugihbcghad, cbafehdcbpedihgbmuefdhigbqihwghn, cbafehdcbpedihgbmuefdhigbqihwghad, cbafehdcbpedihgbmuefdhigbqihbcghn, cbafehdcbpedihgbmuefdhigbqihbcghad, cbafehdcbpedihgbmuefdhigbagihwghn, cbafehdcbpedihgbmuefdhigbagihwghad, cbafehdcbpedihgbmuefdhigbagihbcghn, cbafehdcbpedihgbmuefdhigbagihbcghad, cbafehdcbpedihgbmbofdhigugihwghn, cbafehdcbpedihgbmbofdhigugihwghad, cbafehdcbpedihgbmbofdhigugihbcghn, cbafehdcbpedihgbmbofdhigugihbcghad, cbafehdcbpedihgbmbofdhigbqihwghn, cbafehdcbpedihgbmbofdhigbqihwghad, cbafehdcbpedihgbmbofdhigbqihbcghn, cbafehdcbpedihgbmbofdhigbqihbcghad, cbafehdcbpedihgbmbofdhigbagihwghn, cbafehdcbpedihgbmbofdhigbagihwghad, cbafehdcbpedihgbmbofdhigbagihbcghn, cbafehdcbpedihgbmbofdhigbagihbcghad, cbafehdcbpedihgbmbaefdhigugihwghn, cbafehdcbpedihgbmbaefdhigugihwghad, cbafehdcbpedihgbmbaefdhigugihbcghn, cbafehdcbpedihgbmbaefdhigugihbcghad, cbafehdcbpedihgbmbaefdhigbqihwghn, cbafehdcbpedihgbmbaefdhigbqihwghad, cbafehdcbpedihgbmbaefdhigbqihbcghn, cbafehdcbpedihgbmbaefdhigbqihbcghad, cbafehdcbpedihgbmbaefdhigbagihwghn, cbafehdcbpedihgbmbaefdhigbagihwghad, cbafehdcbpedihgbmbaefdhigbagihbcghn, cbafehdcbpedihgbmbaefdhigbagihbcghad, cbafehdcbpedihgbacuefdhigugihwghn, cbafehdcbpedihgbacuefdhigugihwghad, cbafehdcbpedihgbacuefdhigugihbcghn, cbafehdcbpedihgbacuefdhigugihbcghad, cbafehdcbpedihgbacuefdhigbqihwghn, cbafehdcbpedihgbacuefdhigbqihwghad, cbafehdcbpedihgbacuefdhigbqihbcghn, cbafehdcbpedihgbacuefdhigbqihbcghad, cbafehdcbpedihgbacuefdhigbagihwghn, cbafehdcbpedihgbacuefdhigbagihwghad, cbafehdcbpedihgbacuefdhigbagihbcghn, cbafehdcbpedihgbacuefdhigbagihbcghad, cbafehdcbpedihgbacbofdhigugihwghn, cbafehdcbpedihgbacbofdhigugihwghad, cbafehdcbpedihgbacbofdhigugihbcghn, cbafehdcbpedihgbacbofdhigugihbcghad, cbafehdcbpedihgbacbofdhigbqihwghn, cbafehdcbpedihgbacbofdhigbqihwghad, cbafehdcbpedihgbacbofdhigbqihbcghn, cbafehdcbpedihgbacbofdhigbqihbcghad, cbafehdcbpedihgbacbofdhigbagihwghn, cbafehdcbpedihgbacbofdhigbagihwghad, cbafehdcbpedihgbacbofdhigbagihbcghn, cbafehdcbpedihgbacbofdhigbagihbcghad, cbafehdcbpedihgbacbaefdhigugihwghn, cbafehdcbpedihgbacbaefdhigugihwghad, cbafehdcbpedihgbacbaefdhigugihbcghn, cbafehdcbpedihgbacbaefdhigugihbcghad, cbafehdcbpedihgbacbaefdhigbqihwghn, cbafehdcbpedihgbacbaefdhigbqihwghad, cbafehdcbpedihgbacbaefdhigbqihbcghn, cbafehdcbpedihgbacbaefdhigbqihbcghad, cbafehdcbpedihgbacbaefdhigbagihwghn, cbafehdcbpedihgbacbaefdhigbagihwghad, cbafehdcbpedihgbacbaefdhigbagihbcghn, cbafehdcbpedihgbacbaefdhigbagihbcghad, cbafehdcbafedihgucuefdhigugihwghn, cbafehdcbafedihgucuefdhigugihwghad, cbafehdcbafedihgucuefdhigugihbcghn, cbafehdcbafedihgucuefdhigugihbcghad, cbafehdcbafedihgucuefdhigbqihwghn, cbafehdcbafedihgucuefdhigbqihwghad, cbafehdcbafedihgucuefdhigbqihbcghn, cbafehdcbafedihgucuefdhigbqihbcghad, cbafehdcbafedihgucuefdhigbagihwghn, cbafehdcbafedihgucuefdhigbagihwghad, cbafehdcbafedihgucuefdhigbagihbcghn, cbafehdcbafedihgucuefdhigbagihbcghad, cbafehdcbafedihgucbofdhigugihwghn, cbafehdcbafedihgucbofdhigugihwghad, cbafehdcbafedihgucbofdhigugihbcghn, cbafehdcbafedihgucbofdhigugihbcghad, cbafehdcbafedihgucbofdhigbqihwghn, cbafehdcbafedihgucbofdhigbqihwghad, cbafehdcbafedihgucbofdhigbqihbcghn, cbafehdcbafedihgucbofdhigbqihbcghad, cbafehdcbafedihgucbofdhigbagihwghn, cbafehdcbafedihgucbofdhigbagihwghad, cbafehdcbafedihgucbofdhigbagihbcghn, cbafehdcbafedihgucbofdhigbagihbcghad, cbafehdcbafedihgucbaefdhigugihwghn, cbafehdcbafedihgucbaefdhigugihwghad, cbafehdcbafedihgucbaefdhigugihbcghn, cbafehdcbafedihgucbaefdhigugihbcghad, cbafehdcbafedihgucbaefdhigbqihwghn, cbafehdcbafedihgucbaefdhigbqihwghad, cbafehdcbafedihgucbaefdhigbqihbcghn, cbafehdcbafedihgucbaefdhigbqihbcghad, cbafehdcbafedihgucbaefdhigbagihwghn, cbafehdcbafedihgucbaefdhigbagihwghad, cbafehdcbafedihgucbaefdhigbagihbcghn, cbafehdcbafedihgucbaefdhigbagihbcghad, cbafehdcbafedihgbmuefdhigugihwghn, cbafehdcbafedihgbmuefdhigugihwghad, cbafehdcbafedihgbmuefdhigugihbcghn, cbafehdcbafedihgbmuefdhigugihbcghad, cbafehdcbafedihgbmuefdhigbqihwghn, cbafehdcbafedihgbmuefdhigbqihwghad, cbafehdcbafedihgbmuefdhigbqihbcghn, cbafehdcbafedihgbmuefdhigbqihbcghad, cbafehdcbafedihgbmuefdhigbagihwghn, cbafehdcbafedihgbmuefdhigbagihwghad, cbafehdcbafedihgbmuefdhigbagihbcghn, cbafehdcbafedihgbmuefdhigbagihbcghad, cbafehdcbafedihgbmbofdhigugihwghn, cbafehdcbafedihgbmbofdhigugihwghad, cbafehdcbafedihgbmbofdhigugihbcghn, cbafehdcbafedihgbmbofdhigugihbcghad, cbafehdcbafedihgbmbofdhigbqihwghn, cbafehdcbafedihgbmbofdhigbqihwghad, cbafehdcbafedihgbmbofdhigbqihbcghn, cbafehdcbafedihgbmbofdhigbqihbcghad, cbafehdcbafedihgbmbofdhigbagihwghn, cbafehdcbafedihgbmbofdhigbagihwghad, cbafehdcbafedihgbmbofdhigbagihbcghn, cbafehdcbafedihgbmbofdhigbagihbcghad, cbafehdcbafedihgbmbaefdhigugihwghn, cbafehdcbafedihgbmbaefdhigugihwghad, cbafehdcbafedihgbmbaefdhigugihbcghn, cbafehdcbafedihgbmbaefdhigugihbcghad, cbafehdcbafedihgbmbaefdhigbqihwghn, cbafehdcbafedihgbmbaefdhigbqihwghad, cbafehdcbafedihgbmbaefdhigbqihbcghn, cbafehdcbafedihgbmbaefdhigbqihbcghad, cbafehdcbafedihgbmbaefdhigbagihwghn, cbafehdcbafedihgbmbaefdhigbagihwghad, cbafehdcbafedihgbmbaefdhigbagihbcghn, cbafehdcbafedihgbmbaefdhigbagihbcghad, cbafehdcbafedihgbacuefdhigugihwghn, cbafehdcbafedihgbacuefdhigugihwghad, cbafehdcbafedihgbacuefdhigugihbcghn, cbafehdcbafedihgbacuefdhigugihbcghad, cbafehdcbafedihgbacuefdhigbqihwghn, cbafehdcbafedihgbacuefdhigbqihwghad, cbafehdcbafedihgbacuefdhigbqihbcghn, cbafehdcbafedihgbacuefdhigbqihbcghad, cbafehdcbafedihgbacuefdhigbagihwghn, cbafehdcbafedihgbacuefdhigbagihwghad, cbafehdcbafedihgbacuefdhigbagihbcghn, cbafehdcbafedihgbacuefdhigbagihbcghad, cbafehdcbafedihgbacbofdhigugihwghn, cbafehdcbafedihgbacbofdhigugihwghad, cbafehdcbafedihgbacbofdhigugihbcghn, cbafehdcbafedihgbacbofdhigugihbcghad, cbafehdcbafedihgbacbofdhigbqihwghn, cbafehdcbafedihgbacbofdhigbqihwghad, cbafehdcbafedihgbacbofdhigbqihbcghn, cbafehdcbafedihgbacbofdhigbqihbcghad, cbafehdcbafedihgbacbofdhigbagihwghn, cbafehdcbafedihgbacbofdhigbagihwghad, cbafehdcbafedihgbacbofdhigbagihbcghn, cbafehdcbafedihgbacbofdhigbagihbcghad, cbafehdcbafedihgbacbaefdhigugihwghn, cbafehdcbafedihgbacbaefdhigugihwghad, cbafehdcbafedihgbacbaefdhigugihbcghn, cbafehdcbafedihgbacbaefdhigugihbcghad, cbafehdcbafedihgbacbaefdhigbqihwghn, cbafehdcbafedihgbacbaefdhigbqihwghad, cbafehdcbafedihgbacbaefdhigbqihbcghn, cbafehdcbafedihgbacbaefdhigbqihbcghad, cbafehdcbafedihgbacbaefdhigbagihwghn, cbafehdcbafedihgbacbaefdhigbagihwghad, cbafehdcbafedihgbacbaefdhigbagihbcghn, cbafehdcbafedihgbacbaefdhigbagihbcghad";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(972, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults3() {
        String encoded = "30";
        ArrayList<String> expected = new ArrayList<>();

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(expected,result);
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults4() {
        String encoded = "7213";

        String output = "gbac, gbm, guc";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(3, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults5() {
        String encoded = "191512919";

        String output = "aiaeabiai, aiaeabis, aiaeliai, aiaelis, aioabiai, aioabis, aioliai, aiolis, saeabiai, saeabis, saeliai, saelis, soabiai, soabis, soliai, solis";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(16, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults6() {
        String encoded = "411892119";

        String output = "daahibaai, daahibas, daahibki, daahiuai, daahius, daribaai, daribas, daribki, dariuai, darius, dkhibaai, dkhibas, dkhibki, dkhiuai, dkhius";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(15, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults7() {
        String encoded = "931182119";

        String output = "icaahbaai, icaahbas, icaahbki, icaahuai, icaahus, icarbaai, icarbas, icarbki, icaruai, icarus, ickhbaai, ickhbas, ickhbki, ickhuai, ickhus";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(15, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults8() {
        String encoded = "851291519";

        String output = "heabiaeai, heabiaes, heabioai, heabios, heliaeai, heliaes, helioai, helios";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(8, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults9() {
        String encoded = "2025";

        String output = "bbe, tbe, ty";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(3, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults10() {
        String encoded = "308";

        String output = "ch";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(1, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults11() {
        String encoded = "4200812";

        String output = "dthl, dthab";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(2, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults12() {
        String encoded = "4300812";

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(0, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults13() {
        String encoded = "85121215231518124";

        String output = "heablowaerld, hellaeworld, heaubaebcoahax, heababaebcorax, heabloworabd, heaubaebcaerld, helabobcaerax, heaubaebcorabd, heablowoahax, helabobcoahabd, heaubowoahabd, heablobcaeahabd, heaubowoahax, hellaewoahax, helabaewaeahabd, hellobcorax, heababaeworabd, heabauebcaeahabd, heablobcorax, helabaewoahld, heablaeworld, helabobcorld, hellaeworabd, hellobcoahld, hellowoahax, heablowaeahax, heababobcaeahax, hellowaerld, helabaebcorld, hellaewaeahld, heablaebcaeahax, helauebcorax, helabobcaeahld, hellaebcaeahld, helloworabd, heauuebcaerabd, heablaebcorld, helabaebcaerax, heaubowaerld, heababowaeahabd, heauuebcaeahax, helauebcaerax, hellaebcorax, heababaewoahax, heauuewaeahld, helauewoahabd, heaubaeworld, hellaebcaeahabd, heauuewaerax, helaueworabd, heababaewaerld, heauuewoahabd, heablaebcoahld, hellaewoahabd, hellaebcoahax, helabowoahabd, heabauebcorax, heabaueworld, hellaebcorabd, heabauebcoahld, helauewoahax, heaubaewoahld, heablobcoahabd, heauboworld, heababaebcaeahld, heabauewoahax, hellaebcoahabd, heabauebcaeahax, heaubaewaerax, heablaewoahld, heabloworax, heabauebcaerabd, heablaewaerabd, heababobcaerabd, heabauewaeahax, heablaebcaerabd, helabaewaeahax, helabaewaerabd, heabauewaerabd, helauewaeahax, heablaewaeahax, heabaueworabd, heabauebcaerld, heaubobcorabd, heababaebcorabd, heablaeworabd, hellaebcaerax, heablaebcoahabd, helauewaerabd, heabauebcorld, heablowoahabd, heababaebcaerld, heaubobcaerld, helabaewaerax, helaboworld, heaubobcoahax, heaubaewoahabd, heababaebcoahax, heababowaerabd, heababowaerax, helauewaeahabd, heablaewoahax, heaubaebcaeahld, heaubobcaerabd, heaubobcaeahax, helabaewaeahld, heablobcaeahld, heauueworabd, hellobcorabd, heababowaeahax, heablaewaeahabd, helauebcaeahld, helauebcoahld, helauebcoahabd, heabauewaeahabd, heablaewaeahld, heauuebcaerax, heauueworax, heababaeworax, helabowaerax, heaubaebcoahabd, helabowoahld, heaubaebcoahld, hellaeworax, helauebcaeahabd, heababoworld, heauuebcoahld, heabauebcoahabd, hellobcaerabd, heaubaebcaerax, heaubowoahld, helauewaerld, hellaewaeahabd, heabauewaerld, heablaebcaeahabd, heablowaeahabd, heaubowaeahld, hellaewoahld, helabobcoahax, heababowoahld, helabobcorax, helabaeworax, hellobcoahax, heablowaeahld, heauuewaerld, helabowaeahld, hellobcaeahax, hellowoahld, hellowaerax, heababaewaeahld, heauuebcaeahabd, helauebcorld, heaubobcorax, heababobcoahld, helabaebcaerld, heablaebcaerld, heaubowaerax, heaubaewaeahabd, heaubaeworax, helaueworld, heababobcoahabd, helabobcorabd, heauuebcorld, heababobcaerax, heababaeworld, helabaebcaeahld, heababaebcaerabd, hellowaeahld, heablobcorabd, hellaebcoahld, heababobcorax, heablaebcorabd, heababaewoahabd, heabaueworax, heababaebcaeahabd, helauewoahld, heablobcaerld, heauboworax, heababaebcaeahax, heaubaebcorax, heaubaewoahax, helabowaeahabd, hellaewaerabd, heablobcoahax, heababobcaeahabd, heabauewaerax, heabauewoahabd, heabloworld, heaubaewaerld, helloworld, heababowoahax, heaubaewaerabd, helabaebcoahabd, heabauewaeahld, helaueworax, hellowoahabd, heaubaewaeahax, hellobcaeahabd, hellaewaerax, heababoworabd, heabauebcaerax, heablowoahld, helabaebcorabd, helabaeworabd, heababaebcorld, helabobcaerld, heablaewaerax, heablowaerax, helauebcorabd, heablaeworax, heablobcorld, heauuewaerabd, helabaewoahax, hellobcaerld, heaubobcaeahld, hellaewaeahax, heababobcaeahld, heablaebcaeahld, heauuewoahax, heabauebcorabd, heababowoahabd, heablaebcorax, helabaebcorax, helauebcoahax, heababaewoahld, heauuebcaeahld, heauuewaeahax, heaubaeworabd, helabaebcoahax, heababaewaerax, heablaebcoahax, hellobcoahabd, helabowaerld, helabowoahax, heauuebcoahax, heababoworax, heabauebcoahax, heablaewoahabd, hellowaeahabd, heablaewaerld, heauuebcorabd, helauewaerax, heabauebcaeahld, heabauewoahld, heababobcorabd, heaubowaeahax, helabobcoahld, helloworax, heauuewoahld, hellobcaeahld, helabaeworld, helabowaeahax, hellobcaerax, heababaewaeahax, heaubaebcaerabd, heababobcoahax, heablaebcaerax, heaubobcorld, heababaewaeahabd, helabaebcoahld, helabobcaeahabd, heababobcaerld, heauuebcorax, helauewaeahld, heababobcorld, hellaebcaerld, heaubaebcaeahabd, hellowaerabd, helabaebcaerabd, heababaebcaerax, hellowaeahax, helabaebcaeahax, helabaewoahabd, heaubobcaerax, heauuebcoahabd, helabaewaerld, helaboworax, heababaebcoahabd, heablobcaerax, helabaebcaeahabd, heaubaebcorld, heaubobcoahld, heauuewaeahabd, heababaebcoahld, heaubobcaeahabd, heaubobcoahabd, hellobcorld, heababowaerld, heablobcoahld, heaubaebcaeahax, heaubowaerabd, helabobcaerabd, heablobcaerabd, helauebcaerabd, hellaebcaerabd, helabowaerabd, heablobcaeahax, heablowaerabd, heaubowaeahabd, heababaewaerabd, heaubaewaeahld, heauboworabd, hellaewaerld, helabobcaeahax, hellaebcaeahax, helaboworabd, helauebcaeahax, heababowaeahld, hellaebcorld, helauebcaerld, heauuebcaerld, heauueworld";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(312, result.size());
    }

    @Test
    @Timeout(value = 100, unit = TimeUnit.SECONDS)
    void testSolisDecodedResults14() {
        String encoded = "9113918151413114";

        String output = "iaaciahoadmaad, iamiahonman, iaaciraenman, ikcironmkd, iaaciraenacan, iaaciraeadmkd, iamiahaenman, ikciraenackd, ikciroadackd, ikciahonman, ikciraenman, iaaciahaeadman, iaaciahonackd, iaaciahaenacaad, iaaciahonmkd, ikciahonackd, iamiahaenacaad, iaaciroadacan, iaaciahonacan, iaaciahonman, iaaciraeadacan, iamiahonacaad, ikciahonmkd, ikciahaenman, iamiraenackd, iaaciraeadmaad, ikcironackd, iaaciahoadmkd, iaaciahonacaad, ikciahoadackd, ikciahaenacan, ikciraeadman, iaaciahaeadacan, iamiahoadman, ikciraenmkd, iaaciahaeadmkd, iamiahaeadmaad, iaaciroadman, iamironacaad, iamiahaenackd, iamiahoadmaad, ikciahaeadacaad, ikciraeadackd, ikciahonacaad, iamironackd, iaaciahaenmaad, iamiraeadackd, iaaciraenacaad, ikciraeadacan, iaaciahaeadmaad, ikciahaenmkd, ikcironacan, iamiahonmkd, iaaciahoadman, iamiahaeadman, iamiraenacan, ikciahoadacan, iamiahoadackd, iaaciraenmaad, iaaciraeadacaad, ikciahonmaad, ikciahonacan, ikciraeadmkd, iamiahaeadacan, iamiraenmaad, ikciahaenackd, ikciahoadmaad, iamiroadacaad, ikciraeadmaad, iaaciahaenmkd, ikciahoadman, ikcironmaad, iamironmaad, ikcironacaad, iaacironacan, iamiraeadman, iamiahaenmaad, iamiroadacan, iamiraeadacaad, iamiroadman, iamiahonacan, ikciahaeadmaad, iamiahaeadackd, ikciroadmkd, iaaciahaenackd, iamiahaenacan, ikciahoadacaad, iamiahoadacan, iamiahoadacaad, iaacironacaad, iamiroadmaad, iamiroadmkd, iamironacan, iamironman, iamiahoadmkd, ikciroadacaad, iaacironackd, ikciraenacaad, iaacironmkd, iamiahonackd, iaaciahaeadackd, iaaciahaenacan, iamiahaeadmkd, iaaciroadmkd, iamiraeadacan, ikciahaeadman, ikciahaenacaad, ikciahaenmaad, ikciahaeadmkd, iaaciraenackd, iaaciroadmaad, ikciahaeadackd, ikciraeadacaad, iaaciroadacaad, ikciroadacan, iamiahonmaad, iaaciahaeadacaad, iamiraenmkd, ikciahoadmkd, iamiahaeadacaad, iaaciahoadackd, iamiraeadmaad, iamiraeadmkd, iaaciahonmaad, ikciraenmaad, ikciroadmaad, iamiraenman, iaaciahoadacan, iaaciraenmkd, iaacironmaad, ikcironman, iamiroadackd, iamiahaenmkd, ikciraenacan, iaaciahoadacaad, iaaciroadackd, iaacironman, iaaciahaenman, iaaciraeadackd, ikciroadman, iamironmkd, ikciahaeadacan, iamiraenacaad, iaaciraeadman";
        String[] arr = output.split(", ");
        ArrayList<String> expected = new ArrayList<>(Arrays.asList(arr));

        ArrayList<String> result = TheSolisCode.SolisDecodedResults(encoded);

        assertEquals(new HashSet<>(expected),new HashSet<>(result));
        assertEquals(144, result.size());
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP1() {
        String encoded = "4182113";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(10, result);
    }

    @Test
    @Timeout(value = 60 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP2() {
        String encoded = "41821130912739816020475613782412893647213654761234078612307846712836478912534786123470913985641723641028736198724012836";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(9953280, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP3() {
        String encoded = "30";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(0, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP4() {
        String encoded = "7213";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(3, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP5() {
        String encoded = "191512919";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(16, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP6() {
        String encoded = "411892119";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(15, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP7() {
        String encoded = "931182119";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(15, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP8() {
        String encoded = "851291519";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(8, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP9() {
        String encoded = "2025";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(3, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP10() {
        String encoded = "308";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(1, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP11() {
        String encoded = "4200812";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(2, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP12() {
        String encoded = "4300812";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(0, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP13() {
        String encoded = "85121215231518124";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(312, result);
    }

    @Test
    @Timeout(value = 50 , unit = TimeUnit.MILLISECONDS)
    void testSolisDecodedDP14() {
        String encoded = "9113918151413114";

        int result = TheSolisCode.SolisDecodeDP(encoded);

        assertEquals(144, result);
    }

}